language: ruby

matrix:
  include:
  - rvm: 2.2.3
    env:
      - LABEL=unit_tests
  - rvm: 2.3.0
    env:
      - LABEL=unit_tests
  - rvm: 2.4.1
    env:
      - LABEL=unit_tests
  - rvm: 2.2.9
    env:
      - LABEL=unit_tests
  - rvm: 2.3.6
    env:
      - LABEL=unit_tests
  - rvm: 2.4.3
    env:
      - LABEL=unit_tests
  - rvm: 2.5.0
    env:
      - LABEL=unit_tests

script:
  - bundle install
  - RACK_ENV=test ./bin/seed
  - bundle exec rspec

services:
  - mongodb
